// Code generated by "stringer -type=Index"; DO NOT EDIT.

package m6502

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[X-0]
	_ = x[Y-1]
}

const _Index_name = "XY"

var _Index_index = [...]uint8{0, 1, 2}

func (i Index) String() string {
	if i >= Index(len(_Index_index)-1) {
		return "Index(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Index_name[_Index_index[i]:_Index_index[i+1]]
}
